---
apiVersion: resource.k8s.io/v1beta2
kind: ResourceClaimTemplate
metadata:
  name: ollama-gpu
spec:
  spec:
    devices:
      requests:
        - name: i915
          deviceClassName: gpu.intel.com
